export const questions = [
  { title: 'What activities do you enjoy the most?', group: 'Interests', choices: ['Creating', 'Solving problems', 'Helping people', 'Leading', 'Analyzing', 'Building', 'Communicating', 'Organizing', 'Exploring'] },
  { title: 'What comes naturally to you?', group: 'Strengths', choices: ['Problem solving', 'Communication', 'Leadership', 'Creativity', 'Research', 'Planning', 'Empathy', 'Technology', 'Teaching'] },
  { title: 'What matters most to you?', group: 'Values', choices: ['Impact', 'Growth', 'Independence', 'Stability', 'Community', 'Curiosity', 'Creativity', 'Freedom', 'Collaboration'] },
  { title: 'What would you enjoy spending more time doing?', group: 'Activities', choices: ['Designing', 'Writing', 'Coding', 'Helping others', 'Planning events', 'Making videos', 'Running a project', 'Investigating', 'Presenting'] },
  { title: 'What problems do you like solving?', group: 'Problems', choices: ['People problems', 'Business challenges', 'Technical puzzles', 'Creative briefs', 'Community needs', 'Scientific questions', 'Everyday routines', 'Learning gaps', 'Big ideas'] },
  { title: 'What kind of team feels right?', group: 'Work style', choices: ['Small team', 'Big team', 'Working solo', 'Leading a group', 'Collaborating', 'Meeting people', 'Remote work', 'Hands-on work', 'Still exploring'] },
  { title: 'What would you like to make?', group: 'Making', choices: ['A product', 'A story', 'An app', 'A business', 'A campaign', 'A community', 'A lesson', 'A discovery', 'Something new'] },
  { title: 'What makes you lose track of time?', group: 'Energy', choices: ['Learning', 'Creating', 'Helping', 'Playing with ideas', 'Organizing', 'Building', 'Researching', 'Talking', 'Experimenting'] },
  { title: 'Which skills would you try?', group: 'Skills', choices: ['Design', 'Strategy', 'Data', 'Marketing', 'Teaching', 'Writing', 'Technology', 'Research', 'Leadership'] },
  { title: 'What would you try first?', group: 'First step', choices: ['Create a campaign', 'Design a product', 'Analyze data', 'Build a website', 'Teach a lesson', 'Plan an event', 'Solve a case', 'Interview someone', 'Surprise me'] },
];
export type Field = { id: string; name: string; category: string; summary: string; icon: string; tags: string[]; activities: string[]; careers: string[]; majors: string[]; mission: string };
export const fields: Field[] = [
  { id:'marketing', name:'Marketing', category:'Business & Entrepreneurship', summary:'Connect products and people through ideas, strategy, and communication.', icon:'paperPlane', tags:['Communicating','Creating','Business challenges','Marketing','Writing'], activities:['Create campaigns','Research audiences','Develop brand strategies','Analyze performance'], careers:['Marketing Specialist','Brand Strategist','Content Strategist','Product Marketing'], majors:['Marketing','Business','Communication','Management'], mission:'campaign' },
  { id:'entrepreneurship', name:'Entrepreneurship', category:'Business & Entrepreneurship', summary:'Build ideas, solve problems, and create value.', icon:'rocket', tags:['Leading','Building','Business challenges','Independence'], activities:['Find a problem','Test an idea','Talk to customers','Launch a prototype'], careers:['Founder','Product Owner','Business Developer'], majors:['Business','Management','Entrepreneurship'], mission:'business' },
  { id:'ux', name:'UX Design', category:'Design & Creative', summary:'Make digital experiences easier, clearer, and more human.', icon:'pen', tags:['Creating','Designing','Empathy','Design'], activities:['Interview users','Sketch screens','Prototype ideas','Test designs'], careers:['UX Designer','Product Designer','UX Researcher'], majors:['Design','Informatics','Psychology'], mission:'product' },
  { id:'technology', name:'Technology & Data', category:'Technology & Data', summary:'Use technology and data to solve real problems.', icon:'code', tags:['Technology','Coding','Analyzing','Technical puzzles'], activities:['Build websites','Explore datasets','Test solutions'], careers:['Software Developer','Data Analyst','Product Engineer'], majors:['Computer Science','Information Systems','Statistics'], mission:'website' },
  { id:'healthcare', name:'Healthcare', category:'Healthcare', summary:'Help people live healthier lives with science and care.', icon:'heart', tags:['Helping people','Empathy','Scientific questions'], activities:['Explore health needs','Communicate care','Research solutions'], careers:['Public Health Specialist','Nurse','Health Researcher'], majors:['Medicine','Public Health','Nursing'], mission:'lesson' },
  { id:'education', name:'Education', category:'Education', summary:'Help others learn, grow, and discover new possibilities.', icon:'book', tags:['Teaching','Helping others','Communication'], activities:['Plan a lesson','Explain an idea','Support learners'], careers:['Teacher','Learning Designer','Education Founder'], majors:['Education','Psychology','Communication'], mission:'lesson' },
  { id:'media', name:'Communication & Media', category:'Communication & Media', summary:'Tell stories that inform, connect, and inspire people.', icon:'chat', tags:['Writing','Communicating','Making videos'], activities:['Create content','Interview people','Produce stories'], careers:['Journalist','Content Creator','PR Specialist'], majors:['Communication','Journalism','Media Studies'], mission:'campaign' },
  { id:'science', name:'Science & Research', category:'Science & Research', summary:'Ask better questions and find evidence-based answers.', icon:'spark', tags:['Research','Investigating','Scientific questions'], activities:['Form hypotheses','Collect data','Share findings'], careers:['Researcher','Scientist','Lab Analyst'], majors:['Biology','Physics','Statistics'], mission:'dataset' },
  { id:'social', name:'Social Impact', category:'Social Impact', summary:'Work with communities to make meaningful change.', icon:'globe', tags:['Impact','Community','Helping people'], activities:['Listen to communities','Design initiatives','Measure impact'], careers:['Community Organizer','Policy Analyst','Nonprofit Lead'], majors:['Sociology','Public Policy','Development Studies'], mission:'event' },
  { id:'consulting', name:'Consulting', category:'Business & Entrepreneurship', summary:'Break down complex challenges and help teams find a way forward.', icon:'chart', tags:['Problem solving','Analyzing','Business challenges'], activities:['Research a problem','Present options','Build a recommendation'], careers:['Business Analyst','Strategy Consultant','Operations Consultant'], majors:['Business','Economics','Management'], mission:'business' },
  { id:'engineering', name:'Engineering & Making', category:'Technology & Data', summary:'Design, build and create solutions for the future.', icon:'code', tags:['Building','A product','Problem solving','Hands-on work'], activities:['Sketch a solution','Build a prototype','Test an idea'], careers:['Product Engineer','Mechanical Engineer','Prototype Designer'], majors:['Engineering','Product Design'], mission:'prototype' },
];
export type Mission = { id:string; title:string; field:string; goal:string; time:string; xp:number; skills:string[]; steps:string[]; icon:string };
export const missions: Mission[] = [
  { id:'campaign', title:'Create a Marketing Campaign', field:'marketing', goal:'Create a simple campaign for a product you choose.', time:'2–3 hours', xp:100, skills:['Creativity','Communication','Strategy'], steps:['Choose a product','Define your audience','Create a campaign concept','Design 3 content ideas','Present your result'], icon:'paperPlane' },
  { id:'product', title:'Design a Product', field:'ux', goal:'Sketch a useful solution to an everyday problem.', time:'2 hours', xp:100, skills:['Design','Empathy','Problem solving'], steps:['Find a problem','Interview one person','Sketch your idea','Make a simple prototype','Share what you learned'], icon:'pen' },
  { id:'dataset', title:'Analyze a Dataset', field:'technology', goal:'Find an interesting story hidden in a small dataset.', time:'90 min', xp:80, skills:['Analysis','Curiosity','Communication'], steps:['Pick a dataset','Ask a question','Spot a pattern','Make a chart','Explain your finding'], icon:'chart' },
  { id:'business', title:'Solve a Business Case', field:'entrepreneurship', goal:'Find a practical solution to a small business challenge.', time:'2 hours', xp:100, skills:['Strategy','Research','Presentation'], steps:['Read the brief','Identify the challenge','Explore options','Choose a solution','Pitch your idea'], icon:'rocket' },
  { id:'website', title:'Build a Simple Website', field:'technology', goal:'Make a one-page website for an idea you care about.', time:'3 hours', xp:120, skills:['Technology','Design','Building'], steps:['Choose a topic','Sketch the layout','Build the page','Test it on mobile','Share the link'], icon:'code' },
  { id:'lesson', title:'Teach a Mini Lesson', field:'education', goal:'Help someone understand something you know well.', time:'1 hour', xp:80, skills:['Teaching','Empathy','Communication'], steps:['Choose a topic','Plan 3 key points','Create an example','Teach someone','Ask for feedback'], icon:'book' },
  { id:'event', title:'Organize a Small Event', field:'social', goal:'Bring people together around an idea or cause.', time:'2–3 hours', xp:100, skills:['Leadership','Planning','Collaboration'], steps:['Choose a purpose','Invite a few people','Make a plan','Host the event','Reflect on the outcome'], icon:'globe' },
  { id:'prototype', title:'Build a Simple Prototype', field:'engineering', goal:'Build and test a small solution to an everyday problem.', time:'2 hours', xp:100, skills:['Building','Problem solving','Design'], steps:['Choose an everyday problem','Sketch a solution','Gather simple materials','Build your prototype','Test and share your result'], icon:'code' },
];
export function rankFields(answers: string[][], dream: string) {
  const choices = answers.flat().map(v => v.toLowerCase());
  return [...fields].sort((a,b) => (b.tags.filter(t => choices.includes(t.toLowerCase())).length + (b.id === dream ? 2 : 0)) - (a.tags.filter(t => choices.includes(t.toLowerCase())).length + (a.id === dream ? 2 : 0)));
}
